### PR TITLE
Fix env variables set/get semantics

### LINKED ISSUE #19: No need in set/get env during mongo connection
Why you are doing this? If you set and then get env in code it is far more clear to use a constant. If you want it to be configurable - only GET env and let user set it during app startup, or use program flags (IMO preferred here).

### PR DESCRIPTION
**Pull request by GitH3ll**
Close #19

### CODE REVIEW

File: pkg/mongo/mongo.go [hunk 1]
```diff
@@ -52,10 +50,9 @@ func New(ctx context.Context, dbName string, wg *sync.WaitGroup) (*DB, error) {
 	}
 	users := client.Database(dbName).Collection(usersCollection)
 	tournaments := client.Database(dbName).Collection(tournamentsCollection)
-	buffSize, err := getIntEnvVar(ChanBufferSize)
-	if err != nil {
-		return nil, fmt.Errorf("error handling buffer size: %s", err)
-	}
+	buff := new(int)
+	setFlag(buff, "balancebuff", 20, "balance routines buffer size")
```
Comment (sashayakovtseva) [inline pkg/mongo/mongo.go]: this change doesn't make sense at all. The problem was in set/get semantics, not in in using env vars.

File: cmd/tournaments/main.go [hunk 2]
```diff
@@ -2,20 +2,38 @@ package main
...
+		buff = defaultChanBufferSize
+	}
+
 	ctx, cancel := context.WithCancel(context.Background())
 	defer cancel()
 
-	client, err := mongo.New(ctx, "tournaments")
-	log.Debug("main")
+	client, err := mongo.New(ctx, "tournaments", buff)
+	log.Printf("main")
```
Comment (sashayakovtseva) [inline cmd/tournaments/main.go]: Emmm....

File: pkg/mongo/mongo.go [hunk 3]
```diff
@@ -43,7 +41,7 @@ type (
 
 // New establishes connection to MongoDB. It wraps this connection with DB type and returns this wrapper along with
 // an error value.
-func New(ctx context.Context, dbName string) (*DB, error) {
+func New(ctx context.Context, dbName string, buff int) (*DB, error) {
```
Comment (sashayakovtseva) [inline pkg/mongo/mongo.go]: better name would be bufSize
